Repository Elena-Lou/ft_irc, pull requests merged in 2023-06, with the labels that each got.

#16 MERGE ACOMMAND && NICK:
  ACommand.cpp
  ACommand.hpp
  Channel.cpp
  Channel.hpp
  Client.cpp
  Client.hpp
  Join.cpp
  Join.hpp
  Makefile
  Nick.cpp
  Nick.hpp
  Server.cpp
  Server.hpp
  irc.hpp
Labels: feature

#17 MERGE PARSING FUNCTIONS && KICK:
  Channel.cpp
  Channel.hpp
  Kick.cpp
  Kick.hpp
  Makefile
  Nick.cpp
  Server.cpp
  Server.hpp
  irc.hpp
Labels: feature

#18 MERGE IMPROVED OOP DESTROY CHANNEL && KICK:
  Channel.cpp
  Channel.hpp
  Kick.cpp
  Server.cpp
  Server.hpp
Labels: Rework

#19 MERGE NICK CMD NICK/USER/HOSTNAME REWORK:
  ACommand.cpp
  ACommand.hpp
  Channel.cpp
  Client.cpp
  Client.hpp
  Join.hpp
  Kick.cpp
  Kick.hpp
  Makefile
  Nick.cpp
  Nick.hpp
  Server.cpp
  Server.hpp
  irc.hpp
  main.cpp
Labels: feature

#25 MERGE PASS:
  Client.cpp
  Client.hpp
  Join.cpp
  Join.hpp
  Kick.cpp
  Makefile
  Nick.cpp
  Pass.cpp
  Pass.hpp
  Server.cpp
  Server.hpp
  User.cpp
  irc.hpp
Labels: feature

#26 MERGE PRIVMSG:
  Channel.cpp
  Channel.hpp
  Client.cpp
  Client.hpp
  Join.cpp
  Kick.cpp
  Makefile
  Privmsg.cpp
  Privmsg.hpp
  Server.cpp
  irc.hpp
Labels: feature, fix

#27 Merge KICK:
  Kick.cpp
  Kick.hpp
Labels: feature

#29 MERGE JOIN:
  Channel.cpp
  Channel.hpp
  Join.cpp
  Join.hpp
  Nick.cpp
  Nick.hpp
  Pass.cpp
  Privmsg.cpp
  Server.cpp
  Server.hpp
  User.cpp
  irc.hpp
Labels: feature

#31 MERGE TOPIC:
  Channel.cpp
  Channel.hpp
  Join.cpp
  Kick.cpp
  Makefile
  Nick.cpp
  Privmsg.cpp
  Server.cpp
  Topic.cpp
  Topic.hpp
  User.cpp
  irc.hpp
Labels: feature

#28 MERGE OPER:
  Join.cpp
  Join.hpp
  Kick.cpp
  Kick.hpp
  Oper.cpp
  Oper.hpp
  irc.hpp
Labels: feature

#33 MERGE INVITE:
  Invite.cpp
  Invite.hpp
  Makefile
  Server.cpp
  irc.hpp
Labels: feature, fix

#34 MERGE MODE:
  Channel.cpp
  Channel.hpp
  Invite.cpp
  Join.cpp
  Makefile
  Mode.cpp
  Mode.hpp
  Oper.cpp
  Server.cpp
  irc.hpp
Labels: feature, fix

#35 MERGE PING:
  Makefile
  Mode.cpp
  Ping.cpp
  Ping.hpp
  Server.cpp
  irc.hpp
Labels: feature, fix

#37 MERGE REMOVING DEV MESSAGES:
  Channel.cpp
  Join.cpp
  Kick.cpp
  Makefile
  Mode.cpp
  Oper.hpp
  Privmsg.cpp
  Privmsg.hpp
  Server.cpp
  Topic.cpp
  User.cpp
  irc.hpp
  main.cpp
Labels: feature, fix
